---
- name: Contacting Service now instance
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    requested_by: ''
    short_description: ''
    description: ''
    expected_start: '' 
    # Use this format for date 2021-06-07

  collections:
    - servicenow.servicenow
    
  tasks:
    - name: Creating change request
      servicenow.servicenow.change_request:
        host: "{{ SN_HOST }}" # Instance info provided by custom credential
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"

        state: present
        data:
          short_description: "{{ short_description }}" # Install Cisco Switch
          severity: 3
          priority: 2
      register: snow_var

    - name: list output
      debug: 
        var: snow_var.record.number

    - name: Saving the change request number for later 
      ansible.builtin.set_stats:
        data:
          cr_number: "{{ snow_var.record.number }}"
        per_host: no

    - name: Printing the cr_number
      debug: 
        var: cr_number