---
- name: Connecto SNOW and Schedule CR
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    requested_by: ''
    short_description: ''
    description: ''
    expected_start: '' 
    # Use this format for date 2021-06-07

  collections:
    - servicenow.itsm
    
  tasks:
    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d%H-%M-%S"
      register: tstamp

    - name: Set Expected Time Start variables in format YYYY-MM-DD
      ansible.builtin.set_fact:
        expected_start: "{{ tstamp.stdout[10:]}}"

    - name: Scheduling change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}" # Instance info provided by custom credential
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"

        type: standard
        state: scheduled
        assignment_group:  "Hardware" # some.group
        number: "{{ cr_number }}"
        other:
          expected_start: "{{ expected_start }}" # 2021-06-07
      register: snow_var

    - name: list output
      debug: 
        var: snow_var.record.number

    - name: Saving the change request number for later 
      ansible.builtin.set_stats:
        data:
          cr_number: "{{ snow_var.record.number }}"
        per_host: no